export const TABLE_ACTIONS = {
  NEW_DECK: 'NEW_DECK',
  SET_USER: 'SET_USER_ACTION',
  UNSET_USER: 'UNSET_USER_ACTION',
  REQUEST_START: 'REQUEST_START_USER_ACTION',
  REQUEST_DONE: 'REQUEST_DONE_USER_ACTION',
  LOGOUT: 'LOGOUT',
  USER_FETCH_FAILED: 'USER_FETCH_FAILED',
};

export const deck = (newDeck) => ({
  type: TABLE_ACTIONS.NEW_DECK,
  payload: {
    newDeck
  },
});
